### ISSUE TITLE
Disable edit button when zoomed out too far

### ISSUE THREAD

**Issue by mxdanger** [amandasaurus/waterwaymap.org#54]
When zoomed out far enough away the edit button and the drop down options should be marked as disabled. It should follow the same zoom level that the OSM website uses and similarly display “Zoom in to edit the map” when interacted with.

**Comment by quincylvania** [comment]
I'm not sure there's a need for such a limitation, at least for iD. I think of the Edit button more like "open this area in iD". Maybe I want to check out a region on aerial imagery and then zoom in on a river to edit afterward. The OSM website needs to have constraints to guide for beginners but I assume waterwaymap.org is for more advanced mappers.

**Comment by amandasaurus** [comment]
I'm not terribly opposed to this sort of feature. But I don't want to add too much complexity to WWM.org. I don't want to try to think about matching how OSM.org does things. I'm happy to follow the UNIX approach of just letting the user do what they want.

if someone has a patch then I'll consider it. Otherwise, I'll close this.
