### ISSUE TITLE
Orinoco basin has the same color of Amazon basin (Casiquiare canal bifurcation)

### ISSUE THREAD

**Issue by angoca** [amandasaurus/waterwaymap.org#55]
Orinoco and Amazon are two separate basins, but naturally connected by the Casiquiare river/canal on the Colombian-Venezuelan border. However, they are showed with the same color in the WaterwaysMap.

<img width="634" alt="image" src="https://github.com/amandasaurus/waterwaymap.org/assets/294317/79d88854-c5ab-4928-92c7-561e27af1049">

<img width="616" alt="image" src="https://github.com/amandasaurus/waterwaymap.org/assets/294317/4c5e864f-fb63-4bcd-bce0-9f848110495a">

https://en.wikipedia.org/wiki/Casiquiare_canal

https://en.wikipedia.org/wiki/Amazon_basin

https://en.wikipedia.org/wiki/Orinoco_Basin

Is it possible to have an exception for this case, putting the Casiquiare as part of the Amazon basin and assign a different color for the two basins?

https://waterwaymap.org/#map=14.65/3.13978/-65.87865

**Comment by amandasaurus** [comment]
> Is it possible to have an exception for this case, putting the Casiquiare as part of the Amazon basin and assign a different color for the two basins?

No it's not possible to do a special case like that.

This issue happens in other places. There's a river that splits and flows into the Meditterain and Altantic ([see forum](https://community.openstreetmap.org/t/is-there-a-common-tag-for-underground-infiltrated-watercourses/111558). There's the famous [Parting of the Waters](https://en.wikipedia.org/wiki/Parting_of_the_Waters) in North America too.

At the moment, WWM.org ignores directions, so that can't be easily split. For now.

**Comment by amandasaurus** [comment]
New feature which could be relevant: https://community.openstreetmap.org/t/waterwaymap-org-is-really-going-downhill/115471/1
