### ISSUE TITLE
Oversplified geometries at highest zoom?

### ISSUE THREAD

**Issue by flacombe** [amandasaurus/waterwaymap.org#60]
Hi @amandasaurus 

It's a detail and probably not a problem for topology, I notice that waterways aren't connecting at highest zooms in WWM:
![image](https://github.com/amandasaurus/waterwaymap.org/assets/5690599/b9608157-fd2b-4ce7-aff4-a1453be75677)

Is that an expected behavior or there is some simplification tweak to adopt in vector tiles production?

**Comment by jleedev** [comment]
Looking at the options here: https://github.com/felt/tippecanoe?tab=readme-ov-file#line-and-polygon-simplification, you might try using `--no-simplification-of-shared-nodes`, so that waterways can stay connected.

Perhaps also `--simplification-at-maximum-zoom` to something slightly less than 8, to avoid presenting too much drift at high scales, but I wonder if that might increase the file size significantly.

**Comment by flacombe** [comment]
Sounds good @jleedev, thank you

**Comment by amandasaurus** [comment]
OK, I've [made those changes](https://github.com/amandasaurus/waterwaymap.org/commit/0ba97b55877061dfcbb9a87c18894af77d48be74), we can see tomorrow how it looks.

Initially the vectoritles from tippecanoe were very big (~20GiB! each). It's easy to accidentally make big files. So I tried to dial down the size. But I'd like the map to look nicer.

**Comment by amandasaurus** [comment]
[That area](https://waterwaymap.org/#map=15.32/45.942086/6.643899&tiles=planet-waterway-water) looks  much better now.
![image](https://github.com/user-attachments/assets/10504ac3-23f8-4a11-a7de-4a7072fc57fb)

The data change wasn't much from 6.0 GiB → 6.9 GiB. That's very acceptable for this improvement.

**Comment by flacombe** [comment]
Thank you @amandasaurus, that's way better indeed
