### ISSUE TITLE
Downhill seems to get confused by branching rivers

### ISSUE THREAD

**Issue by jleedev** [amandasaurus/waterwaymap.org#61]
In the 'downhill rivers' layer, the Mississippi River abruptly ends right here: https://waterwaymap.org/#map=13/31.85601/-91.27978&tiles=planet-grouped-ends

![image](https://github.com/amandasaurus/waterwaymap.org/assets/23022/b308250f-a57b-4c29-b1bd-156d8a15f352)

The main river is one way that goes right through this area, but two side streams seem to confound things:

![image](https://github.com/amandasaurus/waterwaymap.org/assets/23022/1465f18c-3ab4-442d-9cfa-40d53b16f177)

**Comment by amandasaurus** [comment]
It looks to be fixed now. [🔗 link](https://waterwaymap.org/#map=12.33/31.86103/-91.25032&tiles=planet-grouped-ends).

![image](https://github.com/user-attachments/assets/766ef2c9-244d-4634-bd0c-8b2cf73dfead)

The gaps in the image are probably due to `tippecanoe` dropping bits. I want to fix that properly.

The current code has a simple method of assigning upstreams when there's certain types of forks, but I & many humans, are not happy with it. I'd like to imrpove that, and have some ideas. That has not been implemented yet.
