### ISSUE TITLE
waterwaymap.org makes sense as host, but not as a source

### ISSUE THREAD

**Issue by matkoniecz** [amandasaurus/waterwaymap.org#62]
see say https://www.openstreetmap.org/changeset/154353146 (topic raised at US Slack)

**Comment by amandasaurus** [comment]
[the discussion on OSMUS slack](https://osmus.slack.com/archives/CCJ2P6KCH/p1722139174936049).

**Comment by amandasaurus** [comment]
I thought `host` (on the changeset) was for the website where (in this case) iD is hosted. Since [WaterwayMap.org](http://waterwaymap.org/) doesn't host iD (or similar), I don't think I should put a link to WWM there.
The pre-filled source from WWM shows which map view the mapper was looking at when the pressed Edit (in this case it's the default) and which map extent. I added the source changeset tag, because that's what the OSMer was looking, or using. when they are making the edit. IMO that's a logical use of `source`.

**Comment by matkoniecz** [comment]
I think that for this [imagery_used](https://wiki.openstreetmap.org/wiki/Key:imagery%20used?uselang=en) would be better fitting

**Comment by amandasaurus** [comment]
but it's not really an imagery… And what if someone uses WWM _and_ Bing to edit the map?

The [`source` on the OSM wiki](https://wiki.openstreetmap.org/wiki/Key:source) says it can be used for things like `[source=survey`](https://wiki.openstreetmap.org/wiki/Key:source#:~:text=semicolon)%20e.g.-,source%3Dsurvey,-%3Bhttps%3A%2F%2Fwww.mapillary), or `[=mapillary`.](https://wiki.openstreetmap.org/wiki/Key:source#:~:text=the%20JOSM%20editor)-,mapillary,-worldwide)

The WWM use of  `source` is similar

**Comment by matkoniecz** [comment]
Using WWM as source seems to be like using `source=JOSM validator` or `source=OSM Carto` to fix issues spotted using those.

**Comment by amandasaurus** [comment]
🤔🤔🤔 If someone is making edits to OSM based on what the JOSM validator says, shouldn't that be recorded somewhere in the changeset metadata? 🤔

**Comment by matkoniecz** [comment]
I would put things like "fixes based on JOSM validator" in changeset description and "source=survey" or "source=common sense" or "source=guess" as source.

**Comment by quincylvania** [comment]
I tend to think the `source` tag is fine for this. If a website provides data that I reference in order to make edits to the map, that's a data source. The validators in JOSM and iD are a bit different since they are integral to the editor itself and can be assumed as such.

In any case, mappers can delete or add to the `source` tag if desired.

**Comment by amandasaurus** [comment]
I'm going to leave it as is.
