### ISSUE TITLE
Edit in ID button

### ISSUE THREAD

**Issue by EwenH** [amandasaurus/waterwaymap.org#63]
Congratulations on an excellent resource..

For those who use the ID editor button, it can be difficult to find the stream, especially in farmland that you wish to improve. This is due to having to zoom in to level 14, locate the waterway in question and then start editing the map. 

1. Can the Edit In ID button open ID with a default zoom level of 16 instead of currently 13? This will render the data layer and initiate the editor rather than 
2. If  the user has zoomed in closer (17 or above), use that zoom level for the OSM ID editor url. This will make it easier for users to commence editing their area of interest

**Comment by amandasaurus** [comment]
The “Edit in iD” button opens at the zoom level that you're currently viewing (cf. [source code](https://github.com/amandasaurus/waterwaymap.org/blob/dbf58d09fd2297fac8d3701d8dbeb9c74d2576e0/docs/js/main.js#L54)).

I can understand how it's an inconvience because iD doesn't show all data (and for very good reasons). However I would to keep the existing zoom. I don't want to “forcibly zoom people in”

**Comment by EwenH** [comment]
Amanda, That sounds logical and thank you for the reply
