### ISSUE TITLE
Filter on tributaries / partial data

### ISSUE THREAD

**Issue by daganzdaanda** [amandasaurus/waterwaymap.org#66]
I really like scrolling around on the waterway map to understand the connection from small creeks to oceans.
Sometimes the coloring of the waterway systems makes it hard to focus on a sub-area of a bigger system. For example at the Danube system in Bavaria, most views will show all the connected rivers in the same color (which makes it easy to find un-connected bits). But if I want to see the "system" of a tributary, I can not make that out easily. With "Named Waterways" you can see all the small named bits in different colors, but not how these connect. 

I guess there is no easy way to make a map for this (what is a tributary?), but maybe an interactive option through Overpass could be added. Maybe the user could select a way or relation and get all the ways that are connected upstream from it somehow? Could that be possible somehow?

**Comment by quincylvania** [comment]
For an example, the USGS stream gage pages have a map for the given point with upstream and downstream segments of the river highlighted. I assume you mean something like this except with all upstream tributaries highlighted?

https://waterdata.usgs.gov/monitoring-location/09505200/

![Screenshot 2024-08-28 at 9 00 04 AM](https://github.com/user-attachments/assets/ba6689dc-5f5c-4945-a581-b7247f957e7d)

**Comment by amandasaurus** [comment]
That would certainly be pretty cool, to have features like this. I'm not sure how to do it though. Perhaps with a lot of rework to generate data a very different format, and some new web interface.

However, I'm going to close this issue, since this is too open ended, and I'd like to keep the issues here clear.
You could try to open a [discussion post](https://github.com/amandasaurus/waterwaymap.org/discussions) about it.
