### ISSUE TITLE
File planet-waterway-stream-ends.geojson is too small

### ISSUE THREAD

**Issue by angoca** [amandasaurus/waterwaymap.org#68]
Hi Amapanda

The file planet-waterway-stream-ends.geojson only has 266 features. It seems there was a problem generating it.
Could you take a look?

<img width="733" alt="image" src="https://github.com/user-attachments/assets/7b18f94f-c565-444a-a246-baff38374b1d">

**Comment by amandasaurus** [comment]
Oops! Thanks for spotting this and alerting me.

I have fixed this now, and there is now a proper data file there.

The bug was due to comments in the [filtering function file](https://github.com/amandasaurus/waterwaymap.org/blob/6126a2382d07d5373cc2f15d7d4dd3169ab4bbe5/flowing_water.tagfilterfunc) not being removed when calculating this,  and [was fixed](https://github.com/amandasaurus/osm-lump-ways/commit/7e820c17d614387eeaf20cbb58a1eba9686489b4) in `osm-lump-ways`.
